function org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp(){var N='bootstrap',O='begin',P='gwt.codesvr.org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp=',Q='gwt.codesvr=',R='org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp',S='startup',T='DUMMY',U=0,V=1,W='iframe',X='position:absolute; width:0; height:0; border:none; left: -1000px;',Y=' top: -1000px;',Z='Chrome',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='script',gb='moduleStartup',hb='moduleRequested',ib='org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp',jb='Failed to load ',kb='head',lb='javascript',mb='meta',nb='name',ob='org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp::',pb='::',qb='gwt:property',rb='content',sb='=',tb='gwt:onPropertyErrorFn',ub='Bad handler "',vb='" for "gwt:onPropertyErrorFn"',wb='gwt:onLoadErrorFn',xb='" for "gwt:onLoadErrorFn"',yb='#',zb='?',Ab='/',Bb='img',Cb='clear.cache.gif',Db='baseUrl',Eb='org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp.nocache.js',Fb='base',Gb='//',Hb='selectingPermutation',Ib='org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp.devmode.js',Jb='508CA25490DDE70223E39EDD1ECCB4C1',Kb=':',Lb='.cache.js',Mb='link',Nb='rel',Ob='stylesheet',Pb='href',Qb='loadExternalRefs',Rb='bootstrap-daterangepicker/daterangepicker.css',Sb='bootstrap-select/css/bootstrap-select.min.css',Tb='uberfire-patternfly.css',Ub='css/patternfly.min.css',Vb='css/patternfly-additions.min.css',Wb='css/bootstrap-datepicker3-1.6.4.min.cache.css',Xb='css/animate-3.5.2.min.cache.css',Yb='css/bootstrap-notify-custom.min.cache.css',Zb='css/card-1.0.1.cache.css',$b='css/bootstrap-slider-9.2.0.min.cache.css',_b='css/bootstrap-datetimepicker-2.4.4.min.cache.css',ac='css/typeahead-0.10.5.min.cache.css',bc='end',cc='http:',dc='file:',ec='_gwt_dummy_',fc='__gwtDevModeHook:org.kie.workbench.common.dmn.showcase.DMNKogitoRuntimeWebapp',gc='Ignoring non-whitelisted Dev Mode URL: ',hc=':moduleBase';var n=window;var o=document;q(N,O);function p(){var a=n.location.search;return a.indexOf(P)!=-1||a.indexOf(Q)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:R,sessionId:n.__gwtStatsSessionId,subSystem:S,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__sendStats=q;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__moduleName=R;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__errFn=null;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__moduleBase=T;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__softPermutationId=U;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__computePropValue=null;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__getPropMap=null;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__installRunAsyncCode=function(){};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__gwtStartLoadingFragment=function(){return null};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__gwt_isKnownPropertyValue=function(){return false};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[R]={moduleName:R};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__moduleStartupDone=function(e){var f=s[R].bindings;s[R].bindings=function(){var a=f?f():{};var b=e[org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__softPermutationId];for(var c=U;c<b.length;c++){var d=b[c];a[d[U]]=d[V]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=o.createElement(W);a.id=R;a.style.cssText=X+Y;a.tabIndex=-1;o.body.appendChild(a);t=a.contentWindow.document;if(navigator.userAgent.indexOf(Z)==-1){t.open();var b=document.compatMode==$?_:ab;t.write(b+bb);t.close()}}
function w(i){function j(a){function b(){if(typeof o.readyState==cb){return typeof o.body!=cb&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(o.removeEventListener){o.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function k(c){function d(a,b){a.removeChild(b)}
var e=u();var f=e.body;var g;if(navigator.userAgent.indexOf(Z)>-1){g=e.createElement(fb);g.text=c.join(ab);f.appendChild(g);d(f,g)}else{for(var h=U;h<c.length;h++){g=e.createElement(fb);g.text=c[h];f.appendChild(g);d(f,g)}}}
org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.onScriptDownloaded=function(a){j(function(){k(a)})};q(gb,hb);var l=o.createElement(fb);l.src=i;if(org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__errFn){l.onerror=function(){org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__errFn(ib,new Error(jb+code))}}o.getElementsByTagName(kb)[U].appendChild(l)}
org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__startLoadingFragment=function(a){return C(a)};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(fb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(mb);for(var g=U,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(nb),k;if(j){j=j.replace(ob,ab);if(j.indexOf(pb)>=U){continue}if(j==qb){k=i.getAttribute(rb);if(k){var l,m=k.indexOf(sb);if(m>=U){j=k.substring(U,m);l=k.substring(m+V)}else{j=k;l=ab}c[j]=l}}else if(j==tb){k=i.getAttribute(rb);if(k){try{d=eval(k)}catch(a){alert(ub+k+vb)}}}else if(j==wb){k=i.getAttribute(rb);if(k){try{e=eval(k)}catch(a){alert(ub+k+xb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(yb);if(b==-1){b=a.length}var c=a.indexOf(zb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ab,Math.min(c,b));return d>=U?a.substring(U,d+V):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(Bb);b.src=a+Cb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Db);if(a!=null){return a}return ab}
function h(){var a=o.getElementsByTagName(fb);for(var b=U;b<a.length;++b){if(a[b].src.indexOf(Eb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=o.getElementsByTagName(Fb);if(a.length>U){return a[a.length-V].href}return ab}
function j(){var a=o.location;return a.href==a.protocol+Gb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(o.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__moduleBase+a}
function D(){var f=[];var g=U;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__computePropValue=j;n.__gwt_activeModules[R].bindings=org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__getPropMap;q(N,Hb);if(p()){return C(Ib)}var k;try{k=Jb;var l=k.indexOf(Kb);if(l!=-1){g=parseInt(k.substring(l+V),eb);k=k.substring(U,l)}}catch(a){}org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__softPermutationId=g;return C(k+Lb)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=o.createElement(Mb);b.setAttribute(Nb,Ob);b.setAttribute(Pb,C(a));o.getElementsByTagName(kb)[U].appendChild(b);__gwt_stylesLoaded[a]=true}}
q(Qb,O);c(Rb);c(Sb);c(Tb);c(Ub);c(Vb);c(Wb);c(Xb);c(Yb);c(Zb);c($b);c(_b);c(ac);q(Qb,bc)}
A();org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__moduleBase=B();s[R].moduleBase=org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.__moduleBase;var G=D();if(n){var H=!!(n.location.protocol==cc||n.location.protocol==dc);n.__gwt_activeModules[R].canRedirect=H;function I(){var b=ec;try{n.sessionStorage.setItem(b,b);n.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=fc;var K=n.sessionStorage[J];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(K)){if(K&&(window.console&&console.log)){console.log(gc+K)}K=ab}if(K&&!n[J]){n[J]=true;n[J+hc]=B();var L=o.createElement(fb);L.src=K;var M=o.getElementsByTagName(kb)[U];M.insertBefore(L,M.firstElementChild||M.children[U]);return false}}}F();q(N,bc);w(G);return true}
org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp.succeeded=org_kie_workbench_common_dmn_showcase_DMNKogitoRuntimeWebapp();